---
- name: step2
  hosts: gluster-servers:gluster-clients
  become: true
  tasks:

    # - name: Import RPM keys
    #   command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY*

    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install yum priorities
      yum:
        name: yum-priorities
        state: latest
